version: '3.7'
services:
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    networks:
      - net

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
    networks:
      - net

  nodejs:
    container_name: nodejs
    image: nodejs
    build:
      context: ./
      dockerfile: ./nodejs/Dockerfile
    ports:
      - "3000:3000"
    restart: always
    networks:
      - net

networks:
  net: